language: php

matrix:
  include:
    - php: 7.1.3
      env: LARAVEL='5.7.*'
    - php: 7.1.3
      env: LARAVEL='5.8.*'
    - php: 7.2
      env: LARAVEL='^6.0'
    - php: 7.2.5
      env: LARAVEL='^7.0'
    - php: 7.3.0
      env: LARAVEL='^8.0'
    - php: nightly
      env: LARAVEL='^8.0'
  fast_finish: true
  allow_failures:
      - php: nightly

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require "illuminate/contracts:${LARAVEL}" --prefer-dist --no-interaction --no-suggest
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest